sudo: required
dist: trusty
services: docker
language: python
python: 3.5
cache:
  timeout: 600

jobs:
  include:

    - stage: integration-test
      os: linux
      install:
          - sudo apt-get -y install nodejs 
          - sudo npm install
      before_script:
          - npm install
      script:
          - mocha $(find test -name 'test.js')
