sudo: required
dist: trusty
services: docker
language: python
python: 3.5
cache:
  timeout: 600

jobs:
  include:
    - stage: integration-test
      os: linux
      env:
      - TEST='NODES_SYNC'
      script:
      - sudo pip install -U docker-compose
      - docker-compose --version
      - "python3 runtest_nodes_synchronize.py"

    - stage: integration-test
      os: linux
      env:
      - TEST='RUN_10MIN'
      script:
      - sudo pip install -U docker-compose
      - docker-compose --version
      - "python3 runtest_nodes_run10mins.py"
