sudo: required
dist: trusty
services: docker
language: python
python: 3.5
cache:
  timeout: 600

jobs:
  include:
    - stage: integration-test
      os: linux
      env:
      - TEST='NODES_SYNC'
      script:
      - docker-compose --version
      - export PYTHONPATH=$(pwd)
      - pytest -s -m oneminaftersync

    - stage: integration-test
      os: linux
      env:
      - TEST='RUN_10MIN'
      script:
      - docker-compose --version
      - export PYTHONPATH=$(pwd)
      - pytest --noconftest -s -m runfor10minutes
