sudo: required
dist: trusty
services: docker
language: python
python: 3.5
cache:
  timeout: 600

jobs:
  include:
    - stage: integration-test
      os: linux
      env:
      - TEST='NODES_SYNC'
      script:
      - sudo pip install -U docker-compose | cat
      - docker-compose --version
      - sudo pip install pytest
      - pytest -s  -m "not custom"

    - stage: integration-test
      os: linux
      env:
      - TEST='RUN_10MIN'
      script:
      - sudo pip install -U docker-compose | cat
      - docker-compose --version
      - sudo pip install pytest
      - pytest --noconftest -s -m runfor10minutes
