version: 2
jobs:
  build:
    # Test mocknet
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: pip install -U -r requirements.txt
      - run: PYTHONPATH=$(pwd) pytest tests/python/basic
      - run: PYTHONPATH=$(pwd) pytest tests/python/mocknet

  tests_xenial:
    # Run all tests in xenial
    docker:
      - image: qrledger/qrl-docker:bionic
    steps:
      - checkout
      - run: pip install -U -r requirements.txt
      - run: PYTHONPATH=$(pwd) pytest tests/python/basic
      - run: PYTHONPATH=$(pwd) pytest tests/python/mocknet
      - run: PYTHONPATH=$(pwd) pytest tests/python/fork_recovery

  tests_bionic:
    # Run all tests in bionic
    docker:
      - image: qrledger/qrl-docker:bionic
    steps:
      - checkout
      - run: pip install -U -r requirements.txt
      - run: PYTHONPATH=$(pwd) pytest tests/python/basic
      - run: PYTHONPATH=$(pwd) pytest tests/python/mocknet
      - run: PYTHONPATH=$(pwd) pytest tests/python/fork_recovery

  tests_js:
    # Run javascript tests
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run: apt-get install -y nodejs
      - run: npm -v
      - run: cd tests/js && npm install && npm test

  debug:
    # debugging job - this can be customize locally but it wont run in circleci
    # to run this, execute circleci build --job debug
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: pip install -U -r requirements.txt
      - run: PYTHONPATH=$(pwd) pytest tests/python/basic


workflows:
  version: 2
  build_all:
    jobs:
      - build
      - tests_xenial
#      - tests_bionic   # FIXME: All tests pass but "Too long with no output" results in an error
      - tests_js
