version: 2
jobs:
  build:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: pip install -U -r requirements.txt
      - run: pytest --ignore=tests/python/helpers

  tests_js:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run: apt-get install -y nodejs
      - run: npm -v
      - run: cd tests_old/js && npm install && npm test

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - tests_js
