version: 2
jobs:
  build:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - run: apt install -y python3-venv
      - checkout
      - run: pip install -U -r requirements.txt
      - run: PYTHONPATH=$(pwd) pytest --ignore=tests/python/helpers

  tests_js:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run: apt-get install -y nodejs
      - run: npm -v
      - run: cd tests/js && npm install && npm test

  tests_fork_recovery:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - run: apt install -y python3-venv
      - checkout
      - run: pip install -U -r requirements.txt
      - run: PYTHONPATH=$(pwd) pytest tests/python/fork_recovery


workflows:
  version: 2
  build_all:
    jobs:
      - build
      - tests_js
      - tests_fork_recovery