version: '3.3'
services:
  node:
    build:
      context: ..
      dockerfile: environments/Dockerfile.qrlnode

    environment:
      - BOOT_PHASE=${BOOT_PHASE}
      - DOCKER_UID=${DOCKER_UID}
      - DOCKER_GID=${DOCKER_GID}
      - LOCALNET_ONLY=${LOCALNET_ONLY}
      - REPO_SLUG=${REPO_SLUG}
      - REPO_BRANCH=${REPO_BRANCH}
      - INTEGRATION_TESTINPLACE=${INTEGRATION_TESTINPLACE}

    image: qrlnode_master

    volumes:
    - ./volumes:/volumes
    - ./nodes_scripts:/root/scripts
    - ./nodes_data:/root/data
    - /var/run/docker.sock:/var/run/docker.sock
